/*
 * Copyright (c) 2014, 2016 Ember
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/* 
 * This file was automatically generated by the DBC parser tool.
 * Rather than making changes here, you should consider updating the
 * parser's templates/DBC definitions and rerunning.
 */

#pragma once 

#include <cstdint>

namespace ember { namespace dbc { namespace disk {

typedef std::uint32_t string_ref;
typedef std::uint32_t uint32;
typedef std::int32_t  int32;
typedef std::uint16_t uint16;
typedef std::int16_t  int16;
typedef std::uint8_t  uint8;
typedef std::int8_t   int8;
typedef std::uint32_t bool32;

#pragma pack(push, 1)

struct StringRefLoc {
	string_ref enGB;
	string_ref koKR;
	string_ref frFR;
	string_ref deDE;
	string_ref enCN;
	string_ref enTW;
	string_ref esES;
	string_ref esMX;
	std::uint32_t flags;
};

typedef StringRefLoc string_ref_loc;

struct ChrClasses {
	typedef int32 PowerType;
	uint32 id;
	uint32 player_class;
	int32 damage_bonus_stat;
	PowerType power_type;
	string_ref pet_name_token;
	string_ref_loc name;
	string_ref filename;
	int32 class_mask;
	bool32 hybrid_class;
};



#pragma pack(pop)

}}} // disk, dbc, ember