/*
 * Copyright (c) 2014, 2016 Ember
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/* 
 * This file was automatically generated by the DBC parser tool.
 * Rather than making changes here, you should consider updating the
 * parser's templates/DBC definitions and rerunning.
 */

#pragma once 

#include <cstdint>
#include <string>

namespace ember { namespace dbc {

struct StringRefLoc {
	std::string enGB;
	std::string koKR;
	std::string frFR;
	std::string deDE;
	std::string enCN;
	std::string enTW;
	std::string esES;
	std::string esMX;
	std::uint32_t flags;
};

struct ChrClasses;

struct ChrClasses {
	enum class PowerType : std::int32_t {
		MANA = 0x00, 
		RAGE = 0x01, 
		FOCUS = 0x02, 
		ENERGY = 0x03, 
		HAPPINESS = 0x04
	};

	std::uint32_t id;
	std::uint32_t player_class;
	std::int32_t damage_bonus_stat;
	PowerType power_type;
	std::string pet_name_token;
	StringRefLoc name;
	std::string filename;
	std::int32_t class_mask;
	std::uint32_t hybrid_class;
};



}} // dbc, ember