# Copyright (c) 2025 Ember
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Linux (GCC) CI
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  # Linux – Cached Debug Build
  Ubuntu_x86_64_debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Cache Dependencies and Homebrew
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            ~/.cache/Homebrew
            dependencies
          key: linux-deps-${{ hashFiles('build_linux.sh') }}
          restore-keys: linux-deps-

      - name: Cache Build Folder
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: build
          key: linux-build-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: linux-build-

      - name: Run Linux Build Script
        run: |
          chmod +x ./build_linux.sh
          ./build_linux.sh
