name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-layer-cache-${{ hashFiles('Dockerfile', '**/*.dockerignore', '**/*.env') }}
        restore-keys: |
          ${{ runner.os }}-docker-layer-cache-

    # Build the Docker image with cache
    - name: Build the Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx build . \
          --file Dockerfile \
          --tag my-image-name:latest \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache