name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Enable BuildKit
    - name: Enable BuildKit
      run: |
        echo '{"experimental":true,"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    # Set up cache for Docker build layers
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Build the Docker image using BuildKit
    - name: Build the Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx . \
          --file Dockerfile \
          --tag my-image-name:$(date +%s) \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache