name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build the Docker image with cache
    - name: Build the Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx build . \
          --file Dockerfile \
          --tag my-image-name:latest \
          --cache-from=type=gha \
          --cache-to=type=gha,mode=max