CREATE DATABASE `ember` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `emberlogin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `emberrealm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'ember'@'localhost' IDENTIFIED BY 'ember';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `ember` . * TO 'ember'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `emberlogin` . * TO 'ember'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `emberrealm` . * TO 'ember'@'localhost';
