CREATE DATABASE `ember` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'ember'@'localhost' IDENTIFIED BY 'ember';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `ember`.* TO 'ember'@'localhost';
