REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'ember'@'localhost';

DROP USER IF EXISTS 'ember'@'localhost';

DROP DATABASE IF EXISTS `ember`;
DROP DATABASE IF EXISTS `emberlogin`;
DROP DATABASE IF EXISTS `emberrealm`;
